/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zhcsumdnpmpxvlptutoi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoY3N1bWRucG1weHZscHR1dG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyMTY0NzUsImV4cCI6MjA5MTc5MjQ3NX0.Y-weW7ty_IkQ7F6fexrMY-W2UADrhPt8Xtnp73xspIE"